package ghoti

import (
	"context"
	"errors"
	"fmt"
	"net"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"syscall"
	"time"
)

// ServerConfig is the subset of the Ghoti configuration the benchmark needs.
type ServerConfig struct {
	Addr        string
	MetricsAddr string
	// SimpleMemorySlots lists the slots configured as simple_memory.
	SimpleMemorySlots []int
	// LogLevel should stay at warn or error so logging does not distort
	// the measurement.
	LogLevel string
	// GOMAXPROCS limits the server cores, 0 leaves the Go default.
	GOMAXPROCS int
}

// YAML renders the configuration file.
func (c ServerConfig) YAML() string {
	var b strings.Builder
	level := c.LogLevel
	if level == "" {
		level = "warn"
	}
	fmt.Fprintf(&b, "# Generated by ghoti-bench\naddr: %q\nprotocol: standard\n", c.Addr)
	fmt.Fprintf(&b, "log:\n  level: %s\n  format: text\n", level)
	if c.MetricsAddr != "" {
		fmt.Fprintf(&b, "metrics:\n  enabled: true\n  addr: %q\n", c.MetricsAddr)
	}
	for _, s := range c.SimpleMemorySlots {
		fmt.Fprintf(&b, "slot_%03d:\n  kind: simple_memory\n", s)
	}
	return b.String()
}

// Server is a running Ghoti process started by the benchmark.
type Server struct {
	Config  ServerConfig
	Dir     string
	LogPath string
	cmd     *exec.Cmd
	exited  chan struct{}
	waitErr error
	stopped bool
}

// ErrAddrInUse reports that a listener address was already taken.
var ErrAddrInUse = errors.New("address already in use")

// startAttempts bounds the retries of StartOnFreePorts.
const startAttempts = 5

// StartOnFreePorts starts the server on free 127.0.0.1 ports for the TCP and
// metrics listeners, ignoring cfg.Addr and cfg.MetricsAddr. Ghoti cannot
// listen on port 0 and report the port it got, so a free port is picked and
// released first; another process can take it before Ghoti binds it. When
// that happens the start is retried with new ports.
func StartOnFreePorts(ctx context.Context, bin *Binary, cfg ServerConfig, dir string) (*Server, error) {
	var err error
	for range startAttempts {
		if cfg.Addr, err = freeAddr(); err != nil {
			return nil, err
		}
		if cfg.MetricsAddr, err = freeAddr(); err != nil {
			return nil, err
		}
		var s *Server
		s, err = Start(ctx, bin, cfg, dir)
		if err == nil || !errors.Is(err, ErrAddrInUse) {
			return s, err
		}
	}
	return nil, fmt.Errorf("no free ports after %d attempts: %w", startAttempts, err)
}

// PID returns the process ID.
func (s *Server) PID() int { return s.cmd.Process.Pid }

// Start writes config.yaml into dir and starts "ghoti run" there. Ghoti looks
// for config.yaml in /etc/ghoti and $HOME/.ghoti before the working
// directory, so Start refuses to run when either one exists, and points HOME
// at dir so a user config can never be picked up.
func Start(ctx context.Context, bin *Binary, cfg ServerConfig, dir string) (*Server, error) {
	if _, err := os.Stat("/etc/ghoti/config.yaml"); err == nil {
		return nil, errors.New("/etc/ghoti/config.yaml exists and would override the benchmark configuration")
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return nil, err
	}
	if err := os.WriteFile(filepath.Join(dir, "config.yaml"), []byte(cfg.YAML()), 0o644); err != nil {
		return nil, err
	}
	logPath := filepath.Join(dir, "server.log")
	logFile, err := os.Create(logPath)
	if err != nil {
		return nil, err
	}

	cmd := exec.Command(bin.Path, "run")
	cmd.Dir = dir
	env := []string{"HOME=" + dir, "PATH=" + os.Getenv("PATH")}
	if cfg.GOMAXPROCS > 0 {
		env = append(env, fmt.Sprintf("GOMAXPROCS=%d", cfg.GOMAXPROCS))
	}
	cmd.Env = env
	cmd.Stdout = logFile
	cmd.Stderr = logFile
	cmd.SysProcAttr = &syscall.SysProcAttr{Setpgid: true}
	if err := cmd.Start(); err != nil {
		logFile.Close()
		return nil, err
	}

	s := &Server{Config: cfg, Dir: dir, LogPath: logPath, cmd: cmd, exited: make(chan struct{})}
	go func() {
		s.waitErr = cmd.Wait()
		logFile.Close()
		close(s.exited)
	}()

	if err := s.waitReady(ctx, 15*time.Second); err != nil {
		s.Stop()
		if logHas(logPath, "address already in use") {
			err = fmt.Errorf("%w: %w", ErrAddrInUse, err)
		}
		return nil, fmt.Errorf("%w (see %s)", err, logPath)
	}
	return s, nil
}

func logHas(path, text string) bool {
	data, err := os.ReadFile(path)
	return err == nil && strings.Contains(string(data), text)
}

// readyGrace is how long the process must stay alive once its ports accept
// connections. If another process holds one of the ports, the dial reaches
// that process while Ghoti fails to bind it and exits, so a Ghoti that is
// still running after the grace period owns its listeners.
const readyGrace = 300 * time.Millisecond

// waitReady waits until the TCP listener, and the metrics listener when
// enabled, accept connections.
func (s *Server) waitReady(ctx context.Context, timeout time.Duration) error {
	deadline := time.Now().Add(timeout)
	addrs := []string{s.Config.Addr}
	if s.Config.MetricsAddr != "" {
		addrs = append(addrs, s.Config.MetricsAddr)
	}
	for _, addr := range addrs {
		for {
			select {
			case <-s.exited:
				return fmt.Errorf("ghoti exited during startup: %v", s.waitErr)
			case <-ctx.Done():
				return ctx.Err()
			default:
			}
			conn, err := net.DialTimeout("tcp", addr, 200*time.Millisecond)
			if err == nil {
				conn.Close()
				break
			}
			if time.Now().After(deadline) {
				return fmt.Errorf("ghoti did not listen on %s within %s", addr, timeout)
			}
			time.Sleep(50 * time.Millisecond)
		}
	}
	select {
	case <-s.exited:
		return fmt.Errorf("ghoti exited during startup: %v", s.waitErr)
	case <-ctx.Done():
		return ctx.Err()
	case <-time.After(readyGrace):
		return nil
	}
}

// stopTimeout is how long Stop waits after SIGTERM. A variable for tests.
var stopTimeout = 10 * time.Second

// freeAddr picks the ports of StartOnFreePorts. A variable for tests.
var freeAddr = FreeAddr

// Stop sends SIGTERM and waits for the process, killing it if it has not
// exited in 10s. It returns an error for anything but a clean exit on
// SIGTERM: a server that exited on its own during the run, one that exited
// with a failure, or one that had to be killed, because any of those means
// the run was not measuring a healthy server. Calling Stop again is a no-op.
func (s *Server) Stop() error {
	if s.stopped {
		return nil
	}
	s.stopped = true

	select {
	case <-s.exited:
		return fmt.Errorf("ghoti exited before it was stopped: %v (see %s)", s.waitErr, s.LogPath)
	default:
	}
	s.cmd.Process.Signal(syscall.SIGTERM)
	select {
	case <-s.exited:
		if s.waitErr != nil {
			return fmt.Errorf("ghoti did not exit cleanly on SIGTERM: %v (see %s)", s.waitErr, s.LogPath)
		}
		return nil
	case <-time.After(stopTimeout):
		syscall.Kill(-s.cmd.Process.Pid, syscall.SIGKILL)
		<-s.exited
		return fmt.Errorf("ghoti did not stop within %s of SIGTERM and was killed (see %s)", stopTimeout, s.LogPath)
	}
}

// FreeAddr returns a 127.0.0.1 address with a currently free port.
func FreeAddr() (string, error) {
	l, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		return "", err
	}
	defer l.Close()
	return l.Addr().String(), nil
}
